import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'gu' | 'kn';

interface Translations {
  home: string;
  donation: string;
  request: string;
  volunteer: string;
  map: string;
  profile: string;
  notifications: string;
  acceptChat: string;
  viewDetails: string;
  getDirections: string;
  donate: string;
  addDonation: string;
  addRequest: string;
  anonymous: string;
  nearbyDonations: string;
  nearbyRequests: string;
  latestActivity: string;
  welcomeMessage: string;
  howItWorks: string;
  accountSettings: string;
  saveChanges: string;
  name: string;
  email: string;
  phone: string;
  location: string;
  language: string;
  totalDonated: string;
  notificationPrefs: string;
  privacySecurity: string;
  helpSupport: string;
  aboutApp: string;
  // Volunteer translations
  available: string;
  myDeliveries: string;
  availableDeliveries: string;
  deliveriesNeedHelp: string;
  noDeliveries: string;
  checkBackLater: string;
  deliveryDetails: string;
  pickupFrom: string;
  deliverTo: string;
  distance: string;
  estimatedTime: string;
  acceptDelivery: string;
  back: string;
  activeDeliveries: string;
  noActiveDeliveries: string;
  acceptDeliveriesToSee: string;
  accepted: string;
  inProgress: string;
  completed: string;
  navigation: string;
  call: string;
  message: string;
  startDelivery: string;
  viewMap: string;
  acceptedAt: string;
  callDonor: string;
  callRecipient: string;
  // Onboarding & Auth translations
  skip: string;
  continue: string;
  getStarted: string;
  chooseYourLanguage: string;
  selectPreferredLanguage: string;
  yourDetails: string;
  letsGetToKnow: string;
  fullName: string;
  enterFullName: string;
  phoneNumber: string;
  emailOptional: string;
  enterEmail: string;
  nameRequired: string;
  nameTooShort: string;
  phoneRequired: string;
  phoneInvalid: string;
  emailInvalid: string;
  digitsRemaining: string;
  otpMessage: string;
  aadharVerification: string;
  enterAadhar: string;
  aadharMustBe12: string;
  dataSecure: string;
  dataSecureDesc: string;
  whyAadhar: string;
  whyAadharPoint1: string;
  whyAadharPoint2: string;
  whyAadharPoint3: string;
  sendOtp: string;
  verifyOtp: string;
  codeSentTo: string;
  resendCode: string;
  resendIn: string;
  didntReceiveCode: string;
  verifyAndContinue: string;
  howWillYouUse: string;
  selectBestDescribes: string;
  donor: string;
  donorDesc: string;
  volunteerDriver: string;
  volunteerDriverDesc: string;
  receiver: string;
  receiverDesc: string;
  verificationNote: string;
  driverLicenseVerification: string;
  driverLicenseDesc: string;
  organizationVerification: string;
  organizationVerificationDesc: string;
  requiredDocuments: string;
  uploadDocuments: string;
  clickOrDrag: string;
  dropFiles: string;
  fileFormats: string;
  uploadedDocuments: string;
  verificationProcess: string;
  verificationProcessDesc: string;
  submitDocuments: string;
  skipVerifyLater: string;
  communityPledge: string;
  maintainSafeCommunity: string;
  iPledgeTo: string;
  pledgePoint1: string;
  pledgePoint2: string;
  pledgePoint3: string;
  pledgePoint4: string;
  pledgeWarning: string;
  agreeToPlege: string;
  iAccept: string;
  // Onboarding slides
  onboardingSlide1Title: string;
  onboardingSlide1Desc: string;
  onboardingSlide2Title: string;
  onboardingSlide2Desc: string;
  onboardingSlide3Title: string;
  onboardingSlide3Desc: string;
}

const translations: Record<Language, Translations> = {
  en: {
    home: 'Home',
    donation: 'Donation',
    request: 'Request',
    volunteer: 'Volunteer',
    map: 'Map',
    profile: 'Profile',
    notifications: 'Notifications',
    acceptChat: 'Accept & Chat',
    viewDetails: 'View Details',
    getDirections: 'Get Directions',
    donate: 'Donate',
    addDonation: 'Add Donation',
    addRequest: 'Add Request',
    anonymous: 'Anonymous',
    nearbyDonations: 'Nearby Donations',
    nearbyRequests: 'Nearby Requests',
    latestActivity: 'Latest Activity',
    welcomeMessage: 'Share what you have, get what you need',
    howItWorks: 'How HelpMate Works',
    accountSettings: 'Account Settings',
    saveChanges: 'Save Changes',
    name: 'Name',
    email: 'Email',
    phone: 'Phone Number',
    location: 'Location',
    language: 'Language',
    totalDonated: 'Total Items Donated',
    notificationPrefs: 'Notification Preferences',
    privacySecurity: 'Privacy & Security',
    helpSupport: 'Help & Support',
    aboutApp: 'About HelpMate',
    available: 'Available',
    myDeliveries: 'My Deliveries',
    availableDeliveries: 'Available Deliveries',
    deliveriesNeedHelp: 'deliveries need your help',
    noDeliveries: 'No Deliveries Available',
    checkBackLater: 'Check back later for new delivery requests',
    deliveryDetails: 'Delivery Details',
    pickupFrom: 'Pickup From',
    deliverTo: 'Deliver To',
    distance: 'Distance',
    estimatedTime: 'Est. Time',
    acceptDelivery: 'Accept Delivery',
    back: 'Back',
    activeDeliveries: 'active deliveries',
    noActiveDeliveries: 'No Active Deliveries',
    acceptDeliveriesToSee: 'Accept deliveries to see them here',
    accepted: 'Accepted',
    inProgress: 'In Progress',
    completed: 'Completed',
    navigation: 'Navigation',
    call: 'Call',
    message: 'Message',
    startDelivery: 'Start Delivery',
    viewMap: 'View Map',
    acceptedAt: 'Accepted',
    callDonor: 'Call Donor',
    callRecipient: 'Call Recipient',
    // Onboarding & Auth translations
    skip: 'Skip',
    continue: 'Continue',
    getStarted: 'Get Started',
    chooseYourLanguage: 'Choose Your Language',
    selectPreferredLanguage: 'Select your preferred language',
    yourDetails: 'Your Details',
    letsGetToKnow: "Let's get to know you",
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    phoneNumber: 'Phone Number',
    emailOptional: 'Email (Optional)',
    enterEmail: 'your.email@example.com',
    nameRequired: 'Name is required',
    nameTooShort: 'Name must be at least 2 characters',
    phoneRequired: 'Phone number is required',
    phoneInvalid: 'Phone number must be 10 digits',
    emailInvalid: 'Invalid email address',
    digitsRemaining: 'digits remaining',
    otpMessage: "We'll send you an OTP to verify your phone number in the next step.",
    aadharVerification: 'Aadhar Verification',
    enterAadhar: 'Enter your 12-digit Aadhar number',
    aadharMustBe12: 'Aadhar number must be 12 digits',
    dataSecure: 'Your data is secure',
    dataSecureDesc: 'We use end-to-end encryption to protect your Aadhar information. Your data will never be shared without your consent.',
    whyAadhar: 'Why do we need Aadhar?',
    whyAadharPoint1: 'Verify your identity to prevent fraud',
    whyAadharPoint2: 'Ensure safe transactions for all users',
    whyAadharPoint3: 'Build trust in the community',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',
    codeSentTo: 'Code sent to',
    resendCode: 'Resend code',
    resendIn: 'Resend code in',
    didntReceiveCode: "Didn't receive the code? Check your messages or wait for the timer to resend.",
    verifyAndContinue: 'Verify & Continue',
    howWillYouUse: 'How will you use HelpMate?',
    selectBestDescribes: 'Select the option that best describes you',
    donor: 'Donor',
    donorDesc: 'I want to donate items to help others in need',
    volunteerDriver: 'Volunteer Driver',
    volunteerDriverDesc: 'I want to deliver donations to those who need them',
    receiver: 'Receiver',
    receiverDesc: 'I need help or donations for myself or my organization',
    verificationNote: 'Based on your selection, you may need to provide additional verification documents in the next step.',
    driverLicenseVerification: 'Driver License Verification',
    driverLicenseDesc: 'As a volunteer driver, we need to verify your driving license',
    organizationVerification: 'Organization Verification',
    organizationVerificationDesc: 'Please provide certificates for your organization',
    requiredDocuments: 'Required Documents',
    uploadDocuments: 'Upload Documents',
    clickOrDrag: 'Click to upload or drag and drop',
    dropFiles: 'Drop files here',
    fileFormats: 'PNG, JPG, or PDF (max 10MB each)',
    uploadedDocuments: 'Uploaded Documents',
    verificationProcess: 'Verification Process',
    verificationProcessDesc: "Your documents will be reviewed within 24-48 hours. You'll receive a notification once verified.",
    submitDocuments: 'Submit Documents',
    skipVerifyLater: 'Skip for now (Verify later)',
    communityPledge: 'Community Integrity Pledge',
    maintainSafeCommunity: 'Help us maintain a safe and honest community',
    iPledgeTo: 'I pledge to:',
    pledgePoint1: 'Use HelpMate honestly and transparently',
    pledgePoint2: 'Provide accurate information in all donation requests',
    pledgePoint3: 'Respect all community members and their contributions',
    pledgePoint4: 'Report any misuse or fraudulent activity',
    pledgeWarning: 'Misuse of this platform, including fraudulent requests or harassment, may result in account suspension and legal action.',
    agreeToPlege: 'I have read and agree to the Community Integrity Pledge and understand the consequences of misuse',
    iAccept: 'I Accept',
    // Onboarding slides
    onboardingSlide1Title: 'Connect & Share',
    onboardingSlide1Desc: 'Create requests for help and connect with generous donors in your community who want to make a real difference.',
    onboardingSlide2Title: 'Get Rewarded',
    onboardingSlide2Desc: 'Earn bonus points and recognition every time you donate or help someone in need. Your kindness matters!',
    onboardingSlide3Title: 'Safe & Verified',
    onboardingSlide3Desc: 'Help verified members with safe, transparent donations and secure transactions. Trust built into every interaction.',
  },
  hi: {
    home: 'होम',
    donation: 'दान',
    request: 'अनुरोध',
    volunteer: 'स्वयंसेवक',
    map: 'नक्शा',
    profile: 'प्रोफ़ाइल',
    notifications: 'सूचनाएं',
    acceptChat: 'स्वीकार करें और चैट करें',
    viewDetails: 'विवरण देखें',
    getDirections: 'दिशा निर्देश',
    donate: 'दान करें',
    addDonation: 'दान जोड़ें',
    addRequest: 'अनुरोध जोड़ें',
    anonymous: 'गुमनाम',
    nearbyDonations: 'आस-पास दान',
    nearbyRequests: 'आस-पास अनुरोध',
    latestActivity: 'नवीनतम गतिविधि',
    welcomeMessage: 'जो है वह साझा करें, जो चाहिए वह प्राप्त करें',
    howItWorks: 'HelpMate कैसे काम करता है',
    accountSettings: 'खाता सेटिंग्स',
    saveChanges: 'परिवर्तन सहेजें',
    name: 'नाम',
    email: 'ईमेल',
    phone: 'फ़ोन नंबर',
    location: 'स्थान',
    language: 'भाषा',
    totalDonated: 'कुल दान की गई वस्तुएं',
    notificationPrefs: 'सूचना प्राथमिकताएं',
    privacySecurity: 'गोपनीयता और सुरक्षा',
    helpSupport: 'सहायता और समर्थन',
    aboutApp: 'HelpMate के बारे में',
    available: 'उपलब्ध',
    myDeliveries: 'मेरी डिलीवरी',
    availableDeliveries: 'उपलब्ध डिलीवरी',
    deliveriesNeedHelp: 'डिलीवरी में आपकी मदद चाहिए',
    noDeliveries: 'कोई डिलीवरी उपलब्ध नहीं',
    checkBackLater: 'नई डिलीवरी अनुरोधों के लिए बाद में जांचें',
    deliveryDetails: 'डिलीवरी विवरण',
    pickupFrom: 'से पिकअप',
    deliverTo: 'को पहुंचाएं',
    distance: 'दूरी',
    estimatedTime: 'अनुमानित समय',
    acceptDelivery: 'डिलीवरी स्वीकार करें',
    back: 'वापस',
    activeDeliveries: 'सक्रिय डिलीवरी',
    noActiveDeliveries: 'कोई सक्रिय डिलीवरी नहीं',
    acceptDeliveriesToSee: 'उन्हें यहां देखने के लिए डिलीवरी स्वीकार करें',
    accepted: 'स्वीकृत',
    inProgress: 'प्रगति में',
    completed: 'पूर्ण',
    navigation: 'नेविगेशन',
    call: 'कॉल',
    message: 'संदेश',
    startDelivery: 'डिलीवरी शुरू करें',
    viewMap: 'मानचित्र देखें',
    acceptedAt: 'स्वीकृत',
    callDonor: 'दाता को कॉल करें',
    callRecipient: 'प्राप्तकर्ता को कॉल करें',
    // Onboarding & Auth translations
    skip: 'छोड़ें',
    continue: 'जारी रखें',
    getStarted: 'शुरू करें',
    chooseYourLanguage: 'अपनी भाषा चुनें',
    selectPreferredLanguage: 'अपनी पसंदीदा भाषा चुनें',
    yourDetails: 'आपका विवरण',
    letsGetToKnow: 'आइए आपको जानते हैं',
    fullName: 'पूरा नाम',
    enterFullName: 'अपना पूरा नाम दर्ज करें',
    phoneNumber: 'फ़ोन नंबर',
    emailOptional: 'ईमेल (वैकल्पिक)',
    enterEmail: 'your.email@example.com',
    nameRequired: 'नाम आवश्यक है',
    nameTooShort: 'नाम कम से कम 2 अक्षर का होना चाहिए',
    phoneRequired: 'फ़ोन नंबर आवश्यक है',
    phoneInvalid: 'फ़ोन नंबर 10 अंकों का होना चाहिए',
    emailInvalid: 'अमान्य ईमेल पता',
    digitsRemaining: 'अंक शेष',
    otpMessage: 'हम अगले चरण में आपके फ़ोन नंबर को सत्यापित करने के लिए आपको एक OTP भेजेंगे।',
    aadharVerification: 'आधार सत्यापन',
    enterAadhar: 'अपना 12 अंकों का आधार नंबर दर्ज करें',
    aadharMustBe12: 'आधार नंबर 12 अंकों का होना चाहिए',
    dataSecure: 'आपका डेटा सुरक्षित है',
    dataSecureDesc: 'हम आपकी आधार जानकारी की सुरक्षा के लिए एंड-टू-एंड एन्क्रिप्शन का उपयोग करते हैं। आपका डेटा आपकी सहमति के बिना कभी साझा नहीं किया जाएगा।',
    whyAadhar: 'हमें आधार की आवश्यकता क्यों है?',
    whyAadharPoint1: 'धोखाधड़ी को रोकने के लिए आपकी पहचान सत्यापित करें',
    whyAadharPoint2: 'सभी उपयोगकर्ताओं के लिए सुरक्षित लेनदेन सुनिश्चित करें',
    whyAadharPoint3: 'समुदाय में विश्वास बनाएं',
    sendOtp: 'OTP भेजें',
    verifyOtp: 'OTP सत्यापित करें',
    codeSentTo: 'कोड भेजा गया',
    resendCode: 'कोड पुनः भेजें',
    resendIn: 'में कोड पुनः भेजें',
    didntReceiveCode: 'कोड प्राप्त नहीं हुआ? अपने संदेश जांचें या पुनः भेजने के लिए टाइमर की प्रतीक्षा करें।',
    verifyAndContinue: 'सत्यापित करें और जारी रखें',
    howWillYouUse: 'आप HelpMate का उपयोग कैसे करेंगे?',
    selectBestDescribes: 'वह विकल्प चुनें जो आपका सर्वोत्तम वर्णन करता है',
    donor: 'दाता',
    donorDesc: 'मैं जरूरतमंदों की मदद के लिए वस्तुएं दान करना चाहता हूं',
    volunteerDriver: 'स्वयंसेवक चालक',
    volunteerDriverDesc: 'मैं जरूरतमंदों को दान पहुंचाना चाहता हूं',
    receiver: 'प्राप्तकर्ता',
    receiverDesc: 'मुझे अपने या अपने संगठन के लिए मदद या दान की आवश्यकता है',
    verificationNote: 'आपके चयन के आधार पर, आपको अगले चरण में अतिरिक्त सत्यापन दस्तावेज़ प्रदान करने की आवश्यकता हो सकती है।',
    driverLicenseVerification: 'ड्राइविंग लाइसेंस सत्यापन',
    driverLicenseDesc: 'एक स्वयंसेवक चालक के रूप में, हमें आपके ड्राइविंग लाइसेंस को सत्यापित करने की आवश्यकता है',
    organizationVerification: 'संगठन सत्यापन',
    organizationVerificationDesc: 'कृपया अपने संगठन के लिए प्रमाणपत्र प्रदान करें',
    requiredDocuments: 'आवश्यक दस्तावेज़',
    uploadDocuments: 'दस्तावेज़ अपलोड करें',
    clickOrDrag: 'अपलोड करने के लिए क्लिक करें या ड्रैग और ड्रॉप करें',
    dropFiles: 'फाइलें यहां छोड़ें',
    fileFormats: 'PNG, JPG, या PDF (प्रत्येक अधिकतम 10MB)',
    uploadedDocuments: 'अपलोड किए गए दस्तावेज़',
    verificationProcess: 'सत्यापन प्रक्रिया',
    verificationProcessDesc: 'आपके दस्तावेज़ों की 24-48 घंटों के भीतर समीक्षा की जाएगी। सत्यापित होने पर आपको एक सूचना प्राप्त होगी।',
    submitDocuments: 'दस्तावेज़ जमा करें',
    skipVerifyLater: 'अभी के लिए छोड़ें (बाद में सत्यापित करें)',
    communityPledge: 'सामुदायिक अखंडता प्रतिज्ञा',
    maintainSafeCommunity: 'हमें एक सुरक्षित और ईमानदार समुदाय बनाए रखने में मदद करें',
    iPledgeTo: 'मैं प्रतिज्ञा करता हूं:',
    pledgePoint1: 'HelpMate का ईमानदारी और पारदर्शिता से उपयोग करें',
    pledgePoint2: 'सभी दान अनुरोधों में सटीक जानकारी प्रदान करें',
    pledgePoint3: 'सभी समुदाय के सदस्यों और उनके योगदान का सम्मान करें',
    pledgePoint4: 'किसी भी दुरुपयोग या धोखाधड़ी की गतिविधि की रिपोर्ट करें',
    pledgeWarning: 'इस प्लेटफ़ॉर्म का दुरुपयोग, जिसमें धोखाधड़ी अनुरोध या उत्पीड़न शामिल है, खाता निलंबन और कानूनी कार्रवाई का कारण बन सकता है।',
    agreeToPlege: 'मैंने सामुदायिक अखंडता प्रतिज्ञा को पढ़ और स्वीकार कर लिया है और दुरुपयोग के परिणामों को समझता हूं',
    iAccept: 'मैं स्वीकार करता हूं',
    // Onboarding slides
    onboardingSlide1Title: 'जुड़ें और साझा करें',
    onboardingSlide1Desc: 'मदद के लिए अनुरोध बनाएं और अपने समुदाय में उदार दाताओं से जुड़ें जो वास्तविक बदलाव लाना चाहते हैं।',
    onboardingSlide2Title: 'पुरस्कार प्राप्त करें',
    onboardingSlide2Desc: 'हर बार जब आप दान करते हैं या किसी जरूरतमंद की मदद करते हैं तो बोनस अंक और मान्यता अर्जित करें। आपकी दयालुता मायने रखती है!',
    onboardingSlide3Title: 'सुरक्षित और सत्यापित',
    onboardingSlide3Desc: 'सुरक्षित, पारदर्शी दान और सुरक्षित लेनदेन के साथ सत्यापित सदस्यों की मदद करें। हर बातचीत में विश्वास बनाया गया है।',
  },
  bn: {
    home: 'হোম',
    donation: 'দান',
    request: 'অনুরোধ',
    volunteer: 'স্বেচ্ছাসেবক',
    map: 'মানচিত্র',
    profile: 'প্রোফাইল',
    notifications: 'বিজ্ঞপ্তি',
    acceptChat: 'গ্রহণ করুন এবং চ্যাট করুন',
    viewDetails: 'বিস্তারিত দেখুন',
    getDirections: 'দিকনির্দেশ',
    donate: 'দান করুন',
    addDonation: 'দান যোগ করুন',
    addRequest: 'অনুরোধ যোগ করুন',
    anonymous: 'বেনামী',
    nearbyDonations: 'কাছাকাছি দান',
    nearbyRequests: 'কাছাকাছি অনুরোধ',
    latestActivity: 'সর্বশেষ কার্যকলাপ',
    welcomeMessage: 'যা আছে শেয়ার করুন, যা প্রয়োজন তা পান',
    howItWorks: 'HelpMate কীভাবে কাজ করে',
    accountSettings: 'অ্যাকাউন্ট সেটিংস',
    saveChanges: 'পরিবর্তন সংরক্ষণ করুন',
    name: 'নাম',
    email: 'ইমেল',
    phone: 'ফোন নম্বর',
    location: 'অবস্থান',
    language: 'ভাষা',
    totalDonated: 'মোট দান করা আইটেম',
    notificationPrefs: 'বিজ্ঞপ্তি পছন্দ',
    privacySecurity: 'গোপনীয়তা এবং নিরাপত্তা',
    helpSupport: 'সাহায্য এবং সমর্থন',
    aboutApp: 'HelpMate সম্পর্কে',
    available: 'উপলব্ধ',
    myDeliveries: 'আমার ডেলিভারি',
    availableDeliveries: 'উপলব্ধ ডেলিভারি',
    deliveriesNeedHelp: 'ডেলিভারিতে আপনার সাহায্য দরকার',
    noDeliveries: 'কোন ডেলিভারি উপলব্ধ নেই',
    checkBackLater: 'নতুন ডেলিভারি অনুরোধের জন্য পরে চেক করুন',
    deliveryDetails: 'ডেলিভারি বিবরণ',
    pickupFrom: 'থেকে পিকআপ',
    deliverTo: 'এ পৌঁছান',
    distance: 'দূরত্ব',
    estimatedTime: 'আনুমানিক সময়',
    acceptDelivery: 'ডেলিভারি গ্রহণ করুন',
    back: 'ফিরে যান',
    activeDeliveries: 'সক্রিয় ডেলিভারি',
    noActiveDeliveries: 'কোন সক্রিয় ডেলিভারি নেই',
    acceptDeliveriesToSee: 'এখানে দেখতে ডেলিভারি গ্রহণ করুন',
    accepted: 'গৃহীত',
    inProgress: 'চলমান',
    completed: 'সম্পন্ন',
    navigation: 'নেভিগেশন',
    call: 'কল',
    message: 'বার্তা',
    startDelivery: 'ডেলিভারি শুরু করুন',
    viewMap: 'মানচিত্র দেখুন',
    acceptedAt: 'গৃহীত',
    callDonor: 'দাতাকে কল করুন',
    callRecipient: 'প্রাপককে কল করুন',
    // Onboarding & Auth translations
    skip: 'এড়িয়ে যান',
    continue: 'চালিয়ে যান',
    getStarted: 'শুরু করুন',
    chooseYourLanguage: 'আপনার ভাষা চয়ন করুন',
    selectPreferredLanguage: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
    yourDetails: 'আপনার বিবরণ',
    letsGetToKnow: 'আসুন আপনাকে জানি',
    fullName: 'পুরো নাম',
    enterFullName: 'আপনার পুরো নাম লিখুন',
    phoneNumber: 'ফোন নম্বর',
    emailOptional: 'ইমেল (ঐচ্ছিক)',
    enterEmail: 'your.email@example.com',
    nameRequired: 'নাম প্রয়োজন',
    nameTooShort: 'নাম কমপক্ষে 2 অক্ষর হতে হবে',
    phoneRequired: 'ফোন নম্বর প্রয়োজন',
    phoneInvalid: 'ফোন নম্বর 10 সংখ্যার হতে হবে',
    emailInvalid: 'অবৈধ ইমেল ঠিকানা',
    digitsRemaining: 'সংখ্যা বাকি',
    otpMessage: 'পরবর্তী ধাপে আপনার ফোন নম্বর যাচাই করতে আমরা আপনাকে একটি OTP পাঠাব।',
    aadharVerification: 'আধার যাচাইকরণ',
    enterAadhar: 'আপনার 12 সংখ্যার আধার নম্বর লিখুন',
    aadharMustBe12: 'আধার নম্বর 12 সংখ্যার হতে হবে',
    dataSecure: 'আপনার ডেটা সুরক্ষিত',
    dataSecureDesc: 'আমরা আপনার আধার তথ্য সুরক্ষিত করতে এন্ড-টু-এন্ড এনক্রিপশন ব্যবহার করি। আপনার সম্মতি ছাড়া আপনার ডেটা কখনই শেয়ার করা হবে না।',
    whyAadhar: 'আমাদের আধার কেন প্রয়োজন?',
    whyAadharPoint1: 'প্রতারণা প্রতিরোধে আপনার পরিচয় যাচাই করুন',
    whyAadharPoint2: 'সকল ব্যবহারকারীর জন্য নিরাপদ লেনদেন নিশ্চিত করুন',
    whyAadharPoint3: 'সম্প্রদায়ে বিশ্বাস তৈরি করুন',
    sendOtp: 'OTP পাঠান',
    verifyOtp: 'OTP যাচাই করুন',
    codeSentTo: 'কোড পাঠানো হয়েছে',
    resendCode: 'কোড পুনরায় পাঠান',
    resendIn: 'এ কোড পুনরায় পাঠান',
    didntReceiveCode: 'কোড পাননি? আপনার বার্তা চেক করুন বা পুনরায় পাঠাতে টাইমারের জন্য অপেক্ষা করুন।',
    verifyAndContinue: 'যাচাই করুন এবং চালিয়ে যান',
    howWillYouUse: 'আপনি কীভাবে HelpMate ব্যবহার করবেন?',
    selectBestDescribes: 'আপনাকে সবচেয়ে ভালভাবে বর্ণনা করে এমন বিকল্প নির্বাচন করুন',
    donor: 'দাতা',
    donorDesc: 'আমি অভাবীদের সাহায্য করতে জিনিসপত্র দান করতে চাই',
    volunteerDriver: 'স্বেচ্ছাসেবক ড্রাইভার',
    volunteerDriverDesc: 'আমি যাদের প্রয়োজন তাদের কাছে দান পৌঁছে দিতে চাই',
    receiver: 'প্রাপক',
    receiverDesc: 'আমার নিজের বা আমার সংস্থার জন্য সাহায্য বা দান প্রয়োজন',
    verificationNote: 'আপনার নির্বাচনের উপর ভিত্তি করে, পরবর্তী ধাপে আপনাকে অতিরিক্ত যাচাইকরণ নথি প্রদান করতে হতে পারে।',
    driverLicenseVerification: 'ড্রাইভিং লাইসেন্স যাচাইকরণ',
    driverLicenseDesc: 'একজন স্বেচ্ছাসেবক ড্রাইভার হিসাবে, আমাদের আপনার ড্রাইভিং লাইসেন্স যাচাই করতে হবে',
    organizationVerification: 'সংস্থা যাচাইকরণ',
    organizationVerificationDesc: 'আপনার সংস্থার জন্য সার্টিফিকেট প্রদান করুন',
    requiredDocuments: 'প্রয়োজনীয় নথি',
    uploadDocuments: 'নথি আপলোড করুন',
    clickOrDrag: 'আপলোড করতে ক্লিক করুন বা ড্র্যাগ এবং ড্রপ করুন',
    dropFiles: 'এখানে ফাইল ড্রপ করুন',
    fileFormats: 'PNG, JPG, বা PDF (প্রতিটি সর্বোচ্চ 10MB)',
    uploadedDocuments: 'আপলোড করা নথি',
    verificationProcess: 'যাচাইকরণ প্রক্রিয়া',
    verificationProcessDesc: 'আপনার নথিগুলি 24-48 ঘন্টার মধ্যে পর্যালোচনা করা হবে। যাচাই হয়ে গেলে আপনি একটি বিজ্ঞপ্তি পাবেন।',
    submitDocuments: 'নথি জমা দিন',
    skipVerifyLater: 'এখনের জন্য এড়িয়ে যান (পরে যাচাই করুন)',
    communityPledge: 'সম্প্রদায় সততা অঙ্গীকার',
    maintainSafeCommunity: 'একটি নিরাপদ এবং সৎ সম্প্রদায় বজায় রাখতে আমাদের সাহায্য করুন',
    iPledgeTo: 'আমি অঙ্গীকার করছি:',
    pledgePoint1: 'সততা এবং স্বচ্ছতার সাথে HelpMate ব্যবহার করুন',
    pledgePoint2: 'সমস্ত দান অনুরোধে সঠিক তথ্য প্রদান করুন',
    pledgePoint3: 'সমস্ত সম্প্রদায়ের সদস্য এবং তাদের অবদানকে সম্মান করুন',
    pledgePoint4: 'যেকোনো অপব্যবহার বা প্রতারণামূলক কার্যকলাপ রিপোর্ট করুন',
    pledgeWarning: 'এই প্ল্যাটফর্মের অপব্যবহার, যার মধ্যে প্রতারণামূলক অনুরোধ বা হয়রানি রয়েছে, অ্যাকাউন্ট স্থগিতকরণ এবং আইনি পদক্ষেপের কারণ হতে পারে।',
    agreeToPlege: 'আমি সম্প্রদায় সততা অঙ্গীকার পড়েছি এবং সম্মত হয়েছি এবং অপব্যবহারের পরিণতি বুঝতে পেরেছি',
    iAccept: 'আমি স্বীকার করি',
    // Onboarding slides
    onboardingSlide1Title: 'সংযুক্ত হন এবং শেয়ার করুন',
    onboardingSlide1Desc: 'সাহায্যের জন্য অনুরোধ তৈরি করুন এবং আপনার সম্প্রদায়ের উদার দাতাদের সাথে সংযুক্ত হন যারা প্রকৃত পরিবর্তন আনতে চান।',
    onboardingSlide2Title: 'পুরস্কার পান',
    onboardingSlide2Desc: 'প্রতিবার আপনি দান করেন বা কাউকে সাহায্য করেন তখন বোনাস পয়েন্ট এবং স্বীকৃতি অর্জন করুন। আপনার দয়া গুরুত্বপূর্ণ!',
    onboardingSlide3Title: 'নিরাপদ এবং যাচাইকৃত',
    onboardingSlide3Desc: 'নিরাপদ, স্বচ্ছ দান এবং সুরক্ষিত লেনদেনের সাথে যাচাইকৃত সদস্যদের সাহায্য করুন। প্রতিটি মিথস্ক্রিয়ায় বিশ্বাস তৈরি।',
  },
  te: {
    home: 'హోమ్',
    donation: 'దానం',
    request: 'అభ్యర్థన',
    volunteer: 'స్వచ్చంద సేవకుడు',
    map: 'మ్యాప్',
    profile: 'ప్రొఫైల్',
    notifications: 'నోటిఫికేషన్లు',
    acceptChat: 'అంగీకరించి చాట్ చేయండి',
    viewDetails: 'వివరాలు చూడండి',
    getDirections: 'దిశలు పొందండి',
    donate: 'దానం చేయండి',
    addDonation: 'దానం జోడించండి',
    addRequest: 'అభ్యర్థన జోడించండి',
    anonymous: 'అనామక',
    nearbyDonations: 'సమీప దానాలు',
    nearbyRequests: 'సమీప అభ్యర్థనలు',
    latestActivity: 'తాజా కార్యాచరణ',
    welcomeMessage: 'మీ దగ్గర ఉన్నది పంచుకోండి, మీకు కావాల్సింది పొందండి',
    howItWorks: 'HelpMate ఎలా పనిచేస్తుంది',
    accountSettings: 'ఖాతా సెట్టింగ్‌లు',
    saveChanges: 'మార్పులను సేవ్ చేయండి',
    name: 'పేరు',
    email: 'ఇమెయిల్',
    phone: 'ఫోన్ నంబర్',
    location: 'స్థానం',
    language: 'భాష',
    totalDonated: 'మొత్తం దానం చేసిన వస్తువులు',
    notificationPrefs: 'నోటిఫికేషన్ ప్రాధాన్యతలు',
    privacySecurity: 'గోప్యత & భద్రత',
    helpSupport: 'సహాయం & మద్దతు',
    aboutApp: 'HelpMate గురించి',
    available: 'అందుబాటులో',
    myDeliveries: 'నా డెలివరీలు',
    availableDeliveries: 'అందుబాటులో ఉన్న డెలివరీలు',
    deliveriesNeedHelp: 'డెలివరీలకు మీ సహాయం అవసరం',
    noDeliveries: 'డెలివరీలు అందుబాటులో లేవు',
    checkBackLater: 'కొత్త డెలివరీ అభ్యర్థనల కోసం తర్వాత తనిఖీ చేయండి',
    deliveryDetails: 'డెలివరీ వివరాలు',
    pickupFrom: 'నుండి పికప్',
    deliverTo: 'కు పంపించండి',
    distance: 'దూరం',
    estimatedTime: 'అంచనా సమయం',
    acceptDelivery: 'డెలివరీని అంగీకరించండి',
    back: 'వెనుకకు',
    activeDeliveries: 'క్రియాశీల డెలివరీలు',
    noActiveDeliveries: 'క్రియాశీల డెలివరీలు లేవు',
    acceptDeliveriesToSee: 'వాటిని ఇక్కడ చూడటానికి డెలివరీలను అంగీకరించండి',
    accepted: 'అంగీకరించబడింది',
    inProgress: 'పురోగతిలో',
    completed: 'పూర్తయింది',
    navigation: 'నావిగేషన్',
    call: 'కాల్',
    message: 'సందేశం',
    startDelivery: 'డెలివరీ ప్రారంభించండి',
    viewMap: 'మ్యాప్ చూడండి',
    acceptedAt: 'అంగీకరించబడింది',
    callDonor: 'దాతను కాల్ చేయండి',
    callRecipient: 'స్వీకరించేవారికి కాల్ చేయండి',
    // Onboarding & Auth translations
    skip: 'దాటవేయండి',
    continue: 'కొనసాగించండి',
    getStarted: 'ప్రారంభించండి',
    chooseYourLanguage: 'మీ భాషను ఎంచుకోండి',
    selectPreferredLanguage: 'మీ ఇష్ట భాషను ఎంచుకోండి',
    yourDetails: 'మీ వివరాలు',
    letsGetToKnow: 'మిమ్మల్ని తెలుసుకుందాం',
    fullName: 'పూర్తి పేరు',
    enterFullName: 'మీ పూర్తి పేరును నమోదు చేయండి',
    phoneNumber: 'ఫోన్ నంబర్',
    emailOptional: 'ఇమెయిల్ (ఐచ్ఛికం)',
    enterEmail: 'your.email@example.com',
    nameRequired: 'పేరు అవసరం',
    nameTooShort: 'పేరు కనీసం 2 అక్షరాలు ఉండాలి',
    phoneRequired: 'ఫోన్ నంబర్ అవసరం',
    phoneInvalid: 'ఫోన్ నంబర్ 10 అంకెలు ఉండాలి',
    emailInvalid: 'చెల్లని ఇమెయిల్ చిరునామా',
    digitsRemaining: 'అంకెలు మిగిలి ఉన్నాయి',
    otpMessage: 'తదుపరి దశలో మీ ఫోన్ నంబర్‌ను ధృవీకరించడానికి మేము మీకు OTP పంపుతాము.',
    aadharVerification: 'ఆధార్ ధృవీకరణ',
    enterAadhar: 'మీ 12-అంకెల ఆధార్ నంబర్‌ను నమోదు చేయండి',
    aadharMustBe12: 'ఆధార్ నంబర్ 12 అంకెలు ఉండాలి',
    dataSecure: 'మీ డేటా సురక్షితం',
    dataSecureDesc: 'మీ ఆధార్ సమాచారాన్ని రక్షించడానికి మేము ఎండ్-టు-ఎండ్ ఎన్‌క్రిప్షన్‌ను ఉపయోగిస్తాము. మీ సమ్మతి లేకుండా మీ డేటా ఎప్పుడూ షేర్ చేయబడదు.',
    whyAadhar: 'మాకు ఆధార్ ఎందుకు అవసరం?',
    whyAadharPoint1: 'మోసాన్ని నివారించడానికి మీ గుర్తింపును ధృవీకరించండి',
    whyAadharPoint2: 'అన్ని వినియోగదారులకు సురక్షిత లావాదేవీలను నిర్ధారించండి',
    whyAadharPoint3: 'సమాజంలో విశ్వాసాన్ని నిర్మించండి',
    sendOtp: 'OTP పంపండి',
    verifyOtp: 'OTP ధృవీకరించండి',
    codeSentTo: 'కోడ్ పంపబడింది',
    resendCode: 'కోడ్‌ను మళ్లీ పంపండి',
    resendIn: 'లో కోడ్‌ను మళ్లీ పంపండి',
    didntReceiveCode: 'కోడ్ అందలేదా? మీ సందేశాలను తనిఖీ చేయండి లేదా మళ్లీ పంపడానికి టైమర్ కోసం వేచి ఉండండి.',
    verifyAndContinue: 'ధృవీకరించండి మరియు కొనసాగించండి',
    howWillYouUse: 'మీరు HelpMate ను ఎలా ఉపయోగిస్తారు?',
    selectBestDescribes: 'మిమ్మల్ని ఉత్తమంగా వివరించే ఎంపికను ఎంచుకోండి',
    donor: 'దాత',
    donorDesc: 'అవసరంలో ఉన్నవారికి సహాయం చేయడానికి నేను వస్తువులను దానం చేయాలనుకుంటున్నాను',
    volunteerDriver: 'స్వచ్ఛంద డ్రైవర్',
    volunteerDriverDesc: 'అవసరమైన వారికి దానాలను అందించాలనుకుంటున్నాను',
    receiver: 'స్వీకర్త',
    receiverDesc: 'నాకు లేదా నా సంస్థకు సహాయం లేదా దానాలు అవసరం',
    verificationNote: 'మీ ఎంపిక ఆధారంగా, తదుపరి దశలో మీరు అదనపు ధృవీకరణ పత్రాలను అందించాల్సి ఉంటుంది.',
    driverLicenseVerification: 'డ్రైవింగ్ లైసెన్స్ ధృవీకరణ',
    driverLicenseDesc: 'స్వచ్ఛంద డ్రైవర్‌గా, మేము మీ డ్రైవింగ్ లైసెన్స్‌ను ధృవీకరించాలి',
    organizationVerification: 'సంస్థ ధృవీకరణ',
    organizationVerificationDesc: 'దయచేసి మీ సంస్థ కోసం ప్రమాణపత్రాలను అందించండి',
    requiredDocuments: 'అవసరమైన పత్రాలు',
    uploadDocuments: 'పత్రాలను అప్‌లోడ్ చేయండి',
    clickOrDrag: 'అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి లేదా డ్రాగ్ మరియు డ్రాప్ చేయండి',
    dropFiles: 'ఫైల్‌లను ఇక్కడ వదలండి',
    fileFormats: 'PNG, JPG, లేదా PDF (ప్రతి గరిష్టంగా 10MB)',
    uploadedDocuments: 'అప్‌లోడ్ చేసిన పత్రాలు',
    verificationProcess: 'ధృవీకరణ ప్రక్రియ',
    verificationProcessDesc: 'మీ పత్రాలు 24-48 గంటల్లో సమీక్షించబడతాయి. ధృవీకరించబడిన తర్వాత మీకు నోటిఫికేషన్ అందుతుంది.',
    submitDocuments: 'పత్రాలను సమర్పించండి',
    skipVerifyLater: 'ఇప్పుడు దాటవేయండి (తర్వాత ధృవీకరించండి)',
    communityPledge: 'సమాజ సమగ్రత ప్రతిజ్ఞ',
    maintainSafeCommunity: 'సురక్షితమైన మరియు నిజాయితీ సమాజాన్ని నిర్వహించడానికి మాకు సహాయం చేయండి',
    iPledgeTo: 'నేను ప్రతిజ్ఞ చేస్తున్నాను:',
    pledgePoint1: 'HelpMate ను నిజాయితీగా మరియు పారదర్శకంగా ఉపయోగించండి',
    pledgePoint2: 'అన్ని దాన అభ్యర్థనలలో ఖచ్చితమైన సమాచారాన్ని అందించండి',
    pledgePoint3: 'అన్ని సమాజ సభ్యులను మరియు వారి సహకారాన్ని గౌరవించండి',
    pledgePoint4: 'ఏదైనా దుర్వినియోగం లేదా మోసపూరిత కార్యకలాపాలను నివేదించండి',
    pledgeWarning: 'మోసపూరిత అభ్యర్థనలు లేదా వేధింపులతో సహా ఈ ప్లాట్‌ఫారమ్ యొక్క దుర్వినియోగం ఖాతా సస్పెన్షన్ మరియు చట్టపరమైన చర్యకు దారితీయవచ్చు.',
    agreeToPlege: 'నేను సమాజ సమగ్రత ప్రతిజ్ఞను చదివాను మరియు అంగీకరించాను మరియు దుర్వినియోగం యొక్క పర్యవసానాలను అర్థం చేసుకున్నాను',
    iAccept: 'నేను అంగీకరిస్తున్నాను',
    // Onboarding slides
    onboardingSlide1Title: 'కనెక్ట్ & షేర్',
    onboardingSlide1Desc: 'సహాయం కోసం అభ్యర్థనలను సృష్టించండి మరియు నిజమైన మార్పు తీసుకురావాలనుకునే మీ సమాజంలోని ఉదార దాతలతో కనెక్ట్ అవ్వండి.',
    onboardingSlide2Title: 'రివార్డ్‌లు పొందండి',
    onboardingSlide2Desc: 'మీరు దానం చేసినప్పుడు లేదా అవసరంలో ఉన్న వారికి సహాయం చేసినప్పుడు ప్రతిసారీ బోనస్ పాయింట్లు మరియు గుర్తింపు పొందండి. మీ దయ ముఖ్యం!',
    onboardingSlide3Title: 'సురక్షితం & ధృవీకరించబడింది',
    onboardingSlide3Desc: 'సురక్షితమైన, పారదర్శకమైన దానాలు మరియు సురక్షిత లావాదేవీలతో ధృవీకరించబడిన సభ్యులకు సహాయం చేయండి. ప్రతి పరస్పర చర్యలో విశ్వాసం నిర్మించబడింది.',
  },
  mr: {
    home: 'होम',
    donation: 'देणगी',
    request: 'विनंती',
    volunteer: 'स्वयंसेवक',
    map: 'नकाशा',
    profile: 'प्रोफाईल',
    notifications: 'सूचना',
    acceptChat: 'स्वीकारा आणि चॅट करा',
    viewDetails: 'तपशील पहा',
    getDirections: 'दिशानिर्देश',
    donate: 'दान करा',
    addDonation: 'देणगी जोडा',
    addRequest: 'विनंती जोडा',
    anonymous: 'अनामिक',
    nearbyDonations: 'जवळपासच्या देणग्या',
    nearbyRequests: 'जवळपासच्या विनंत्या',
    latestActivity: 'नवीनतम क्रियाकलाप',
    welcomeMessage: 'तुमच्याकडे जे आहे ते शेअर करा, तुम्हाला जे हवे ते मिळवा',
    howItWorks: 'HelpMate कसे काम करते',
    accountSettings: 'खाते सेटिंग्ज',
    saveChanges: 'बदल जतन करा',
    name: 'नाव',
    email: 'ईमेल',
    phone: 'फोन नंबर',
    location: 'स्थान',
    language: 'भाषा',
    totalDonated: 'एकूण दान केलेल्या वस्तू',
    notificationPrefs: 'सूचना प्राधान्ये',
    privacySecurity: 'गोपनीयता आणि सुरक्षा',
    helpSupport: 'मदत आणि समर्थन',
    aboutApp: 'HelpMate बद्दल',
    available: 'उपलब्ध',
    myDeliveries: 'माझी डिलिव्हरी',
    availableDeliveries: 'उपलब्ध डिलिव्हरी',
    deliveriesNeedHelp: 'डिलिव्हरीला तुमची मदत हवी आहे',
    noDeliveries: 'कोणतीही डिलिव्हरी उपलब्ध नाही',
    checkBackLater: 'नवीन डिलिव्हरी विनंत्यांसाठी नंतर तपासा',
    deliveryDetails: 'डिलिव्हरी तपशील',
    pickupFrom: 'येथून पिकअप',
    deliverTo: 'येथे पोहोचवा',
    distance: 'अंतर',
    estimatedTime: 'अंदाजे वेळ',
    acceptDelivery: 'डिलिव्हरी स्वीकारा',
    back: 'परत',
    activeDeliveries: 'सक्रिय डिलिव्हरी',
    noActiveDeliveries: 'कोणतीही सक्रिय डिलिव्हरी नाही',
    acceptDeliveriesToSee: 'येथे पाहण्यासाठी डिलिव्हरी स्वीकारा',
    accepted: 'स्वीकारले',
    inProgress: 'प्रगतीपथावर',
    completed: 'पूर्ण झाले',
    navigation: 'नेव्हिगेशन',
    call: 'कॉल',
    message: 'संदेश',
    startDelivery: 'डिलिव्हरी सुरू करा',
    viewMap: 'नकाशा पहा',
    acceptedAt: 'स्वीकारले',
    callDonor: 'दात्याला कॉल करा',
    callRecipient: 'प्राप्तकर्त्याला कॉल करा',
    // Onboarding & Auth translations
    skip: 'वगळा',
    continue: 'सुरू ठेवा',
    getStarted: 'सुरुवात करा',
    chooseYourLanguage: 'तुमची भाषा निवडा',
    selectPreferredLanguage: 'तुमची पसंतीची भाषा निवडा',
    yourDetails: 'तुमचे तपशील',
    letsGetToKnow: 'तुम्हाला जाणून घेऊया',
    fullName: 'पूर्ण नाव',
    enterFullName: 'तुमचे पूर्ण नाव प्रविष्ट करा',
    phoneNumber: 'फोन नंबर',
    emailOptional: 'ईमेल (पर्यायी)',
    enterEmail: 'your.email@example.com',
    nameRequired: 'नाव आवश्यक आहे',
    nameTooShort: 'नाव किमान 2 वर्णांचे असले पाहिजे',
    phoneRequired: 'फोन नंबर आवश्यक आहे',
    phoneInvalid: 'फोन नंबर 10 अंकांचा असला पाहिजे',
    emailInvalid: 'अवैध ईमेल पत्ता',
    digitsRemaining: 'अंक उरले',
    otpMessage: 'पुढील चरणात तुमचा फोन नंबर सत्यापित करण्यासाठी आम्ही तुम्हाला OTP पाठवू.',
    aadharVerification: 'आधार सत्यापन',
    enterAadhar: 'तुमचा 12-अंकी आधार नंबर प्रविष्ट करा',
    aadharMustBe12: 'आधार नंबर 12 अंकांचा असला पाहिजे',
    dataSecure: 'तुमचा डेटा सुरक्षित आहे',
    dataSecureDesc: 'तुमची आधार माहिती संरक्षित करण्यासाठी आम्ही एंड-टू-एंड एन्क्रिप्शन वापरतो. तुमची संमती शिवाय तुमचा डेटा कधीही शेअर केला जाणार नाही.',
    whyAadhar: 'आम्हाला आधारची आवश्यकता का आहे?',
    whyAadharPoint1: 'फसवणूक टाळण्यासाठी तुमची ओळख सत्यापित करा',
    whyAadharPoint2: 'सर्व वापरकर्त्यांसाठी सुरक्षित व्यवहार सुनिश्चित करा',
    whyAadharPoint3: 'समुदायात विश्वास निर्माण करा',
    sendOtp: 'OTP पाठवा',
    verifyOtp: 'OTP सत्यापित करा',
    codeSentTo: 'कोड पाठवला',
    resendCode: 'कोड पुन्हा पाठवा',
    resendIn: 'मध्ये कोड पुन्हा पाठवा',
    didntReceiveCode: 'कोड मिळाला नाही? तुमचे संदेश तपासा किंवा पुन्हा पाठवण्यासाठी टायमरची प्रतीक्षा करा.',
    verifyAndContinue: 'सत्यापित करा आणि सुरू ठेवा',
    howWillYouUse: 'तुम्ही HelpMate कसे वापराल?',
    selectBestDescribes: 'तुमचे सर्वोत्तम वर्णन करणारा पर्याय निवडा',
    donor: 'दाता',
    donorDesc: 'मला गरजूंना मदत करण्यासाठी वस्तू दान करायच्या आहेत',
    volunteerDriver: 'स्वयंसेवक चालक',
    volunteerDriverDesc: 'मला गरजू लोकांना देणग्या पोहोचवायच्या आहेत',
    receiver: 'प्राप्तकर्ता',
    receiverDesc: 'मला माझ्यासाठी किंवा माझ्या संस्थेसाठी मदत किंवा देणग्या हव्या आहेत',
    verificationNote: 'तुमच्या निवडीवर आधारित, तुम्हाला पुढील चरणात अतिरिक्त सत्यापन दस्तऐवज प्रदान करावे लागतील.',
    driverLicenseVerification: 'ड्रायव्हिंग लायसन्स सत्यापन',
    driverLicenseDesc: 'स्वयंसेवक चालक म्हणून, आम्हाला तुमचे ड्रायव्हिंग लायसन्स सत्यापित करणे आवश्यक आहे',
    organizationVerification: 'संस्था सत्यापन',
    organizationVerificationDesc: 'कृपया तुमच्या संस्थेसाठी प्रमाणपत्रे प्रदान करा',
    requiredDocuments: 'आवश्यक कागदपत्रे',
    uploadDocuments: 'दस्तऐवज अपलोड करा',
    clickOrDrag: 'अपलोड करण्यासाठी क्लिक करा किंवा ड्रॅग आणि ड्रॉप करा',
    dropFiles: 'फाइल्स येथे सोडा',
    fileFormats: 'PNG, JPG, किंवा PDF (प्रत्येकी कमाल 10MB)',
    uploadedDocuments: 'अपलोड केलेले दस्तऐवज',
    verificationProcess: 'सत्यापन प्रक्रिया',
    verificationProcessDesc: 'तुमच्या दस्तऐवजांचे 24-48 तासांत पुनरावलोकन केले जाईल. सत्यापित झाल्यावर तुम्हाला सूचना मिळेल.',
    submitDocuments: 'दस्तऐवज सबमिट करा',
    skipVerifyLater: 'आत्ता वगळा (नंतर सत्यापित करा)',
    communityPledge: 'समुदाय अखंडता प्रतिज्ञा',
    maintainSafeCommunity: 'सुरक्षित आणि प्रामाणिक समुदाय राखण्यात आम्हाला मदत करा',
    iPledgeTo: 'मी प्रतिज्ञा करतो:',
    pledgePoint1: 'HelpMate प्रामाणिकपणे आणि पारदर्शकपणे वापरा',
    pledgePoint2: 'सर्व देणगी विनंत्यांमध्ये अचूक माहिती प्रदान करा',
    pledgePoint3: 'सर्व समुदाय सदस्यांचा आणि त्यांच्या योगदानाचा आदर करा',
    pledgePoint4: 'कोणत्याही गैरवापर किंवा फसव्या क्रियाकलापांची तक्रार करा',
    pledgeWarning: 'फसव्या विनंत्या किंवा छळवणूक यासह या प्लॅटफॉर्मचा गैरवापर खाते निलंबन आणि कायदेशीर कारवाईस कारणीभूत ठरू शकतो.',
    agreeToPlege: 'मी समुदाय अखंडता प्रतिज्ञा वाचली आहे आणि त्यास सहमती दिली आहे आणि गैरवापराचे परिणाम समजतो',
    iAccept: 'मी स्वीकारतो',
    // Onboarding slides
    onboardingSlide1Title: 'कनेक्ट आणि शेअर करा',
    onboardingSlide1Desc: 'मदतीसाठी विनंत्या तयार करा आणि तुमच्या समुदायातील उदार दात्यांशी कनेक्ट व्हा जे खरा फरक करू इच्छितात.',
    onboardingSlide2Title: 'बक्षिसे मिळवा',
    onboardingSlide2Desc: 'प्रत्येक वेळी जेव्हा तुम्ही देणगी देता किंवा गरजू व्यक्तीला मदत करता तेव्हा बोनस गुण आणि ओळख मिळवा. तुमची दयाळूपणा महत्त्वाची आहे!',
    onboardingSlide3Title: 'सुरक्षित आणि सत्यापित',
    onboardingSlide3Desc: 'सुरक्षित, पारदर्शक देणग्या आणि सुरक्षित व्यवहारांसह सत्यापित सदस्यांना मदत करा. प्रत्येक संवादात विश्वास निर्माण झालेला.',
  },
  ta: {
    home: 'முகப்பு',
    donation: 'நன்கொடை',
    request: 'கோரிக்கை',
    volunteer: 'தன்னார்வலர்',
    map: 'வரைபடம்',
    profile: 'சுயவிவரம்',
    notifications: 'அறிவிப்புகள்',
    acceptChat: 'ஏற்று அரட்டை',
    viewDetails: 'விவரங்களைக் காண்க',
    getDirections: 'திசைகளைப் பெறுக',
    donate: 'நன்கொடை அளி',
    addDonation: 'நன்கொடை சேர்',
    addRequest: 'கோரிக்கை சேர்',
    anonymous: 'அநாமதேய',
    nearbyDonations: 'அருகிலுள்ள நன்கொடைகள்',
    nearbyRequests: 'அருகிலுள்ள கோரிக்கைகள்',
    latestActivity: 'சமீபத்திய செயல்பாடு',
    welcomeMessage: 'உங்களிடம் உள்ளதைப் பகிருங்கள், உங்களுக்குத் தேவையானதைப் பெறுங்கள்',
    howItWorks: 'HelpMate எவ்வாறு செயல்படுகிறது',
    accountSettings: 'கணக்கு அமைப்புகள்',
    saveChanges: 'மாற்றங்களைச் சேமி',
    name: 'பெயர்',
    email: 'மின்னஞ்சல்',
    phone: 'தொலைபேசி எண்',
    location: 'இடம்',
    language: 'மொழி',
    totalDonated: 'மொத்த நன்கொடை பொருட்கள்',
    notificationPrefs: 'அறிவிப்பு விருப்பத்தேர்வுகள்',
    privacySecurity: 'தனியுரிமை மற்றும் பாதுகாப்பு',
    helpSupport: 'உதவி மற்றும் ஆதரவு',
    aboutApp: 'HelpMate பற்றி',
    available: 'கிடைக்கும்',
    myDeliveries: 'என் விநியோகங்கள்',
    availableDeliveries: 'கிடைக்கும் விநியோகங்கள்',
    deliveriesNeedHelp: 'விநியோகங்களுக்கு உங்கள் உதவி தேவை',
    noDeliveries: 'விநியோகங்கள் இல்லை',
    checkBackLater: 'புதிய விநியோக கோரிக்கைகளுக்கு பின்னர் சரிபார்க்கவும்',
    deliveryDetails: 'விநியோக விவரங்கள்',
    pickupFrom: 'இருந்து எடு',
    deliverTo: 'க்கு வழங்கு',
    distance: 'தூரம்',
    estimatedTime: 'மதிப்பிடப்பட்ட நேரம்',
    acceptDelivery: 'விநியோகத்தை ஏற்கவும்',
    back: 'பின்',
    activeDeliveries: 'செயலில் உள்ள விநியோகங்கள்',
    noActiveDeliveries: 'செயலில் உள்ள விநியோகங்கள் இல்லை',
    acceptDeliveriesToSee: 'இங்கே பார்க்க விநியோகங்களை ஏற்கவும்',
    accepted: 'ஏற்கப்பட்டது',
    inProgress: 'நடைபெறுகிறது',
    completed: 'முடிந்தது',
    navigation: 'வழிசெலுத்தல்',
    call: 'அழை',
    message: 'செய்தி',
    startDelivery: 'விநியோகத்தைத் தொடங்கு',
    viewMap: 'வரைபடத்தைக் காண்க',
    acceptedAt: 'ஏற்கப்பட்டது',
    callDonor: 'நன்கொடையாளரை அழைக்கவும்',
    callRecipient: 'பெறுநரை அழைக்கவும்',
    // Onboarding & Auth translations
    skip: 'தவிர்க்கவும்',
    continue: 'தொடரவும்',
    getStarted: 'தொடங்குங்கள்',
    chooseYourLanguage: 'உங்கள் மொழியைத் தேர்வு செய்யுங்கள்',
    selectPreferredLanguage: 'உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்',
    yourDetails: 'உங்கள் விவரங்கள்',
    letsGetToKnow: 'உங்களை அறிந்துகொள்வோம்',
    fullName: 'முழுப் பெயர்',
    enterFullName: 'உங்கள் முழுப் பெயரை உள்ளிடவும்',
    phoneNumber: 'தொலைபேசி எண்',
    emailOptional: 'மின்னஞ்சல் (விருப்பத்தேர்வு)',
    enterEmail: 'your.email@example.com',
    nameRequired: 'பெயர் தேவை',
    nameTooShort: 'பெயர் குறைந்தது 2 எழுத்துக்களாக இருக்க வேண்டும்',
    phoneRequired: 'தொலைபேசி எண் தேவை',
    phoneInvalid: 'தொலைபேசி எண் 10 இலக்கங்களாக இருக்க வேண்டும்',
    emailInvalid: 'தவறான மின்னஞ்சல் முகவரி',
    digitsRemaining: 'இலக்கங்கள் மீதமுள்ளன',
    otpMessage: 'அடுத்த படியில் உங்கள் தொலைபேசி எண்ணைச் சரிபார்க்க நாங்கள் உங்களுக்கு OTP அனுப்புவோம்.',
    aadharVerification: 'ஆதார் சரிபார்ப்பு',
    enterAadhar: 'உங்கள் 12-இலக்க ஆதார் எண்ணை உள்ளிடவும்',
    aadharMustBe12: 'ஆதார் எண் 12 இலக்கங்களாக இருக்க வேண்டும்',
    dataSecure: 'உங்கள் தரவு பாதுகாப்பானது',
    dataSecureDesc: 'உங்கள் ஆதார் தகவலைப் பாதுகாக்க நாங்கள் எண்ட்-டு-எண்ட் என்க்ரிப்ஷனைப் பயன்படுத்துகிறோம். உங்கள் ஒப்புதல் இல்லாமல் உங்கள் தரவு பகிரப்படாது.',
    whyAadhar: 'எங்களுக்கு ஆதார் ஏன் தேவை?',
    whyAadharPoint1: 'மோசடியைத் தடுக்க உங்கள் அடையாளத்தைச் சரிபார்க்கவும்',
    whyAadharPoint2: 'அனைத்து பயனர்களுக்கும் பாதுகாப்பான பரிவர்த்தனைகளை உறுதிசெய்யவும்',
    whyAadharPoint3: 'சமூகத்தில் நம்பிக்கையை வளர்க்கவும்',
    sendOtp: 'OTP அனுப்பவும்',
    verifyOtp: 'OTP சரிபார்க்கவும்',
    codeSentTo: 'குறியீடு அனுப்பப்பட்டது',
    resendCode: 'குறியீட்டை மீண்டும் அனுப்பவும்',
    resendIn: 'இல் குறியீட்டை மீண்டும் அனுப்பவும்',
    didntReceiveCode: 'குறியீட்டைப் பெறவில்லையா? உங்கள் செய்திகளைச் சரிபார்க்கவும் அல்லது மீண்டும் அனுப்ப டைமரைக் காத்திருக்கவும்.',
    verifyAndContinue: 'சரிபார்த்து தொடரவும்',
    howWillYouUse: 'நீங்கள் HelpMate ஐ எவ்வாறு பயன்படுத்துவீர்கள்?',
    selectBestDescribes: 'உங்களை சிறப்பாக விவரிக்கும் விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
    donor: 'நன்கொடையாளர்',
    donorDesc: 'தேவையுள்ளவர்களுக்கு உதவ நான் பொருட்களை நன்கொடையாக வழங்க விரும்புகிறேன்',
    volunteerDriver: 'தன்னார்வ ஓட்டுநர்',
    volunteerDriverDesc: 'தேவைப்படுபவர்களுக்கு நன்கொடைகளை வழங்க விரும்புகிறேன்',
    receiver: 'பெறுநர்',
    receiverDesc: 'எனக்கு அல்லது எனது நிறுவனத்திற்கு உதவி அல்லது நன்கொடைகள் தேவை',
    verificationNote: 'உங்கள் தேர்வின் அடிப்படையில், அடுத்த படியில் நீங்கள் கூடுதல் சரிபார்ப்பு ஆவணங்களை வழங்க வேண்டியிருக்கலாம்.',
    driverLicenseVerification: 'ஓட்டுநர் உரிமச் சரிபார்ப்பு',
    driverLicenseDesc: 'தன்னார்வ ஓட்டுநராக, உங்கள் ஓட்டுநர் உரிமத்தைச் சரிபார்க்க வேண்டும்',
    organizationVerification: 'நிறுவனச் சரிபார்ப்பு',
    organizationVerificationDesc: 'உங்கள் நிறுவனத்திற்கான சான்றிதழ்களை வழங்கவும்',
    requiredDocuments: 'தேவையான ஆவணங்கள்',
    uploadDocuments: 'ஆவணங்களைப் பதிவேற்றவும்',
    clickOrDrag: 'பதிவேற்ற கிளிக் செய்யவும் அல்லது இழுத்து விடவும்',
    dropFiles: 'கோப்புகளை இங்கே விடவும்',
    fileFormats: 'PNG, JPG, அல்லது PDF (ஒவ்வொன்றும் அதிகபட்சம் 10MB)',
    uploadedDocuments: 'பதிவேற்றப்பட்ட ஆவணங்கள்',
    verificationProcess: 'சரிபார்ப்பு செயல்முறை',
    verificationProcessDesc: 'உங்கள் ஆவணங்கள் 24-48 மணி நேரத்திற்குள் மதிப்பாய்வு செய்யப்படும். சரிபார்க்கப்பட்டவுடன் உங்களுக்கு அறிவிப்பு கிடைக்கும்.',
    submitDocuments: 'ஆவணங்களைச் சமர்ப்பிக்கவும்',
    skipVerifyLater: 'இப்போது தவிர்க்கவும் (பின்னர் சரிபார்க்கவும்)',
    communityPledge: 'சமூக நேர்மை உறுதிமொழி',
    maintainSafeCommunity: 'பாதுகாப்பான மற்றும் நேர்மையான சமூகத்தைப் பேண எங்களுக்கு உதவவும்',
    iPledgeTo: 'நான் உறுதியளிக்கிறேன்:',
    pledgePoint1: 'HelpMate ஐ நேர்மையாகவும் வெளிப்படையாகவும் பயன்படுத்துங்கள்',
    pledgePoint2: 'அனைத்து நன்கொடை கோரிக்கைகளிலும் துல்லியமான தகவலை வழங்கவும்',
    pledgePoint3: 'அனைத்து சமூக உறுப்பினர்களையும் அவர்களின் பங்களிப்புகளையும் மதிக்கவும்',
    pledgePoint4: 'எந்தவொரு தவறான பயன்பாடு அல்லது மோசடி நடவடிக்கையையும் புகாரளிக்கவும்',
    pledgeWarning: 'மோசடி கோரிக்கைகள் அல்லது துன்புறுத்தல் உட்பட இந்த தளத்தின் தவறான பயன்பாடு கணக்கு இடைநிறுத்தம் மற்றும் சட்ட நடவடிக்கைக்கு வழிவகுக்கும்.',
    agreeToPlege: 'நான் சமூக நேர்மை உறுதிமொழியைப் படித்து ஒப்புக்கொண்டேன் மற்றும் தவறான பயன்பாட்டின் விளைவுகளைப் புரிந்துகொள்கிறேன்',
    iAccept: 'நான் ஏற்றுக்கொள்கிறேன்',
    // Onboarding slides
    onboardingSlide1Title: 'இணைத்து பகிரவும்',
    onboardingSlide1Desc: 'உதவிக்கான கோரிக்கைகளை உருவாக்கி, உண்மையான மாற்றத்தை ஏற்படுத்த விரும்பும் உங்கள் சமூகத்தில் உள்ள தாராள நன்கொடையாளர்களுடன் இணைக்கவும்.',
    onboardingSlide2Title: 'வெகுமதிகளைப் பெறுங்கள்',
    onboardingSlide2Desc: 'நீங்கள் நன்கொடை அளிக்கும் ஒவ்வொரு முறையும் அல்லது தேவையுள்ள ஒருவருக்கு உதவும்போது போனஸ் புள்ளிகள் மற்றும் அங்கீகாரம் பெறுங்கள். உங்கள் கருணை முக்கியம்!',
    onboardingSlide3Title: 'பாதுகாப்பான & சரிபார்க்கப்பட்டது',
    onboardingSlide3Desc: 'பாதுகாப்பான, வெளிப்படையான நன்கொடைகள் மற்றும் பாதுகாப்பான பரிவர்த்தனைகளுடன் சரிபார்க்கப்பட்ட உறுப்பினர்களுக்கு உதவவும். ஒவ்வொரு தொடர்புக்குள்ளும் நம்பிக்கை கட்டமைக்கப்பட்டுள்ளது.',
  },
  gu: {
    home: 'હોમ',
    donation: 'દાન',
    request: 'વિનંતી',
    volunteer: 'સ્વયંસેવક',
    map: 'નકશો',
    profile: 'પ્રોફાઇલ',
    notifications: 'સૂચનાઓ',
    acceptChat: 'સ્વીકારો અને ચેટ કરો',
    viewDetails: 'વિગતો જુઓ',
    getDirections: 'દિશાનિર્દેશો',
    donate: 'દાન આપો',
    addDonation: 'દાન ઉમેરો',
    addRequest: 'વિનંતી ઉમેરો',
    anonymous: 'અનામી',
    nearbyDonations: 'નજીકના દાન',
    nearbyRequests: 'નજીકની વિનંતીઓ',
    latestActivity: 'તાજેતરની પ્રવૃત્તિ',
    welcomeMessage: 'તમારી પાસે જે છે તે શેર કરો, તમને જે જોઈએ છે તે મેળવો',
    howItWorks: 'HelpMate કેવી રીતે કામ કરે છે',
    accountSettings: 'એકાઉન્ટ સેટિંગ્સ',
    saveChanges: 'ફેરફારો સાચવો',
    name: 'નામ',
    email: 'ઈમેઇલ',
    phone: 'ફોન નંબર',
    location: 'સ્થાન',
    language: 'ભાષા',
    totalDonated: 'કુલ દાન કરેલી વસ્તુઓ',
    notificationPrefs: 'સૂચના પસંદગીઓ',
    privacySecurity: 'ગોપનીયતા અને સુરક્ષા',
    helpSupport: 'મદદ અને સપોર્ટ',
    aboutApp: 'HelpMate વિશે',
    available: 'ઉપલબ્ધ',
    myDeliveries: 'મારી ડિલિવરીઓ',
    availableDeliveries: 'ઉપલબ્ધ ડિલિવરીઓ',
    deliveriesNeedHelp: 'ડિલિવરીઓને તમારી મદદની જરૂર છે',
    noDeliveries: 'કોઈ ડિલિવરી ઉપલબ્ધ નથી',
    checkBackLater: 'નવી ડિલિવરી વિનંતીઓ માટે પછીથી તપાસો',
    deliveryDetails: 'ડિલિવરી વિગતો',
    pickupFrom: 'થી પિકઅપ',
    deliverTo: 'ને પહોંચાડો',
    distance: 'અંતર',
    estimatedTime: 'અંદાજિત સમય',
    acceptDelivery: 'ડિલિવરી સ્વીકારો',
    back: 'પાછળ',
    activeDeliveries: 'સક્રિય ડિલિવરીઓ',
    noActiveDeliveries: 'કોઈ સક્રિય ડિલિવરીઓ નથી',
    acceptDeliveriesToSee: 'તેમને અહીં જોવા માટે ડિલિવરીઓ સ્વીકારો',
    accepted: 'સ્વીકૃત',
    inProgress: 'પ્રગતિમાં',
    completed: 'પૂર્ણ',
    navigation: 'નેવિગેશન',
    call: 'કૉલ',
    message: 'સંદેશ',
    startDelivery: 'ડિલિવરી શરૂ કરો',
    viewMap: 'નકશો જુઓ',
    acceptedAt: 'સ્વીકૃત',
    callDonor: 'દાતાને કૉલ કરો',
    callRecipient: 'પ્રાપ્તકર્તાને કૉલ કરો',
    // Onboarding & Auth translations
    skip: 'છોડો',
    continue: 'ચાલુ રાખો',
    getStarted: 'પ્રારંભ કરો',
    chooseYourLanguage: 'તમારી ભાષા પસંદ કરો',
    selectPreferredLanguage: 'તમારી પસંદીદા ભાષા પસંદ કરો',
    yourDetails: 'તમારી વિગતો',
    letsGetToKnow: 'ચાલો તમને જાણીએ',
    fullName: 'પૂરું નામ',
    enterFullName: 'તમારું પૂરું નામ દાખલ કરો',
    phoneNumber: 'ફોન નંબર',
    emailOptional: 'ઈમેઇલ (વૈકલ્પિક)',
    enterEmail: 'your.email@example.com',
    nameRequired: 'નામ જરૂરી છે',
    nameTooShort: 'નામ ઓછામાં ઓછા 2 અક્ષરોનું હોવું જોઈએ',
    phoneRequired: 'ફોન નંબર જરૂરી છે',
    phoneInvalid: 'ફોન નંબર 10 અંકોનો હોવો જોઈએ',
    emailInvalid: 'અમાન્ય ઈમેઇલ સરનામું',
    digitsRemaining: 'અંકો બાકી',
    otpMessage: 'અમે આગલા પગલામાં તમારા ફોન નંબરને ચકાસવા માટે તમને OTP મોકલીશું.',
    aadharVerification: 'આધાર ચકાસણી',
    enterAadhar: 'તમારો 12-અંકનો આધાર નંબર દાખલ કરો',
    aadharMustBe12: 'આધાર નંબર 12 અંકોનો હોવો જોઈએ',
    dataSecure: 'તમારો ડેટા સુરક્ષિત છે',
    dataSecureDesc: 'અમે તમારી આધાર માહિતીને સુરક્ષિત કરવા માટે એન્ડ-ટુ-એન્ડ એન્ક્રિપ્શનનો ઉપયોગ કરીએ છીએ. તમારી સંમતિ વિના તમારો ડેટા ક્યારેય શેર કરવામાં આવશે નહીં.',
    whyAadhar: 'અમને આધારની શા માટે જરૂર છે?',
    whyAadharPoint1: 'છેતરપિંડી અટકાવવા માટે તમારી ઓળખ ચકાસો',
    whyAadharPoint2: 'બધા વપરાશકર્તાઓ માટે સુરક્ષિત વ્યવહારો સુનિશ્ચિત કરો',
    whyAadharPoint3: 'સમુદાયમાં વિશ્વાસ બનાવો',
    sendOtp: 'OTP મોકલો',
    verifyOtp: 'OTP ચકાસો',
    codeSentTo: 'કોડ મોકલ્યો',
    resendCode: 'કોડ ફરીથી મોકલો',
    resendIn: 'માં કોડ ફરીથી મોકલો',
    didntReceiveCode: 'કોડ મળ્યો નથી? તમારા સંદેશાઓ તપાસો અથવા ફરીથી મોકલવા માટે ટાઈમરની રાહ જુઓ.',
    verifyAndContinue: 'ચકાસો અને ચાલુ રાખો',
    howWillYouUse: 'તમે HelpMate નો ઉપયોગ કેવી રીતે કરશો?',
    selectBestDescribes: 'તમારું શ્રેષ્ઠ વર્ણન કરતો વિકલ્પ પસંદ કરો',
    donor: 'દાતા',
    donorDesc: 'હું જરૂરિયાતમંદોને મદદ કરવા માટે વસ્તુઓ દાન કરવા માંગુ છું',
    volunteerDriver: 'સ્વયંસેવક ડ્રાઈવર',
    volunteerDriverDesc: 'હું જરૂરિયાતમંદોને દાન પહોંચાડવા માંગુ છું',
    receiver: 'પ્રાપ્તકર્તા',
    receiverDesc: 'મને મારા અથવા મારી સંસ્થા માટે મદદ અથવા દાનની જરૂર છે',
    verificationNote: 'તમારી પસંદગીના આધારે, તમારે આગલા પગલામાં વધારાના ચકાસણી દસ્તાવેજો પ્રદાન કરવાની જરૂર પડી શકે છે.',
    driverLicenseVerification: 'ડ્રાઈવિંગ લાઇસન્સ ચકાસણી',
    driverLicenseDesc: 'સ્વયંસેવક ડ્રાઈવર તરીકે, અમારે તમારા ડ્રાઈવિંગ લાઇસન્સને ચકાસવાની જરૂર છે',
    organizationVerification: 'સંસ્થા ચકાસણી',
    organizationVerificationDesc: 'કૃપા કરીને તમારી સંસ્થા માટે પ્રમાણપત્રો પ્રદાન કરો',
    requiredDocuments: 'જરૂરી દસ્તાવેજો',
    uploadDocuments: 'દસ્તાવેજો અપલોડ કરો',
    clickOrDrag: 'અપલોડ કરવા માટે ક્લિક કરો અથવા ડ્રેગ અને ડ્રોપ કરો',
    dropFiles: 'ફાઇલો અહીં મૂકો',
    fileFormats: 'PNG, JPG, અથવા PDF (દરેક મહત્તમ 10MB)',
    uploadedDocuments: 'અપલોડ કરેલા દસ્તાવેજો',
    verificationProcess: 'ચકાસણી પ્રક્રિયા',
    verificationProcessDesc: 'તમારા દસ્તાવેજોની 24-48 કલાકમાં સમીક્ષા કરવામાં આવશે. ચકાસાયા પછી તમને સૂચના મળશે.',
    submitDocuments: 'દસ્તાવેજો સબમિટ કરો',
    skipVerifyLater: 'હમણાં માટે છોડો (પછીથી ચકાસો)',
    communityPledge: 'સમુદાય અખંડિતતા પ્રતિજ્ઞા',
    maintainSafeCommunity: 'સુરક્ષિત અને પ્રામાણિક સમુદાય જાળવવામાં અમને મદદ કરો',
    iPledgeTo: 'હું પ્રતિજ્ઞા લઉં છું:',
    pledgePoint1: 'HelpMate નો પ્રામાણિકપણે અને પારદર્શક રીતે ઉપયોગ કરો',
    pledgePoint2: 'તમામ દાન વિનંતીઓમાં સચોટ માહિતી પ્રદાન કરો',
    pledgePoint3: 'તમામ સમુદાય સભ્યો અને તેમના યોગદાનનો આદર કરો',
    pledgePoint4: 'કોઈપણ દુરુપયોગ અથવા છેતરપિંડીની પ્રવૃત્તિની જાણ કરો',
    pledgeWarning: 'છેતરપિંડી વિનંતીઓ અથવા સતાવણી સહિત આ પ્લેટફોર્મનો દુરુપયોગ એકાઉન્ટ સસ્પેન્શન અને કાનૂની કાર્યવાહીમાં પરિણમી શકે છે.',
    agreeToPlege: 'મેં સમુદાય અખંડિતતા પ્રતિજ્ઞા વાંચી છે અને સંમત છું અને દુરુપયોગના પરિણામો સમજું છું',
    iAccept: 'હું સ્વીકારું છું',
    // Onboarding slides
    onboardingSlide1Title: 'જોડાઓ અને શેર કરો',
    onboardingSlide1Desc: 'મદદ માટે વિનંતીઓ બનાવો અને તમારા સમુદાયમાં ઉદાર દાતાઓ સાથે જોડાઓ જેઓ વાસ્તવિક ફરક લાવવા માંગે છે.',
    onboardingSlide2Title: 'પુરસ્કારો મેળવો',
    onboardingSlide2Desc: 'દર વખતે જ્યારે તમે દાન કરો છો અથવા જરૂરિયાતમંદની મદદ કરો છો ત્યારે બોનસ પોઇન્ટ્સ અને માન્યતા મેળવો. તમારી દયા મહત્વની છે!',
    onboardingSlide3Title: 'સુરક્ષિત અને ચકાસાયેલ',
    onboardingSlide3Desc: 'સુરક્ષિત, પારદર્શક દાન અને સુરક્ષિત વ્યવહારો સાથે ચકાસાયેલ સભ્યોને મદદ કરો. દરેક ક્રિયામાં વિશ્વાસ બાંધવામાં આવ્યો છે.',
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    donation: 'ದಾನ',
    request: 'ವಿನಂತಿ',
    volunteer: 'ಸ್ವಯಂಸೇವಕ',
    map: 'ನಕ್ಷೆ',
    profile: 'ಪ್ರೊಫೈಲ್',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    acceptChat: 'ಸ್ವೀಕರಿಸಿ ಮತ್ತು ಚಾಟ್ ಮಾಡಿ',
    viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    getDirections: 'ನಿರ್ದೇಶನಗಳನ್ನು ಪಡೆಯಿರಿ',
    donate: 'ದಾನ ಮಾಡಿ',
    addDonation: 'ದಾನ ಸೇರಿಸಿ',
    addRequest: 'ವಿನಂತಿ ಸೇರಿಸಿ',
    anonymous: 'ಅನಾಮಧೇಯ',
    nearbyDonations: 'ಹತ್ತಿರದ ದಾನಗಳು',
    nearbyRequests: 'ಹತ್ತಿರದ ವಿನಂತಿಗಳು',
    latestActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    welcomeMessage: 'ನಿಮ್ಮ ಬಳಿ ಇರುವುದನ್ನು ಹಂಚಿಕೊಳ್ಳಿ, ನಿಮಗೆ ಬೇಕಾದುದನ್ನು ಪಡೆಯಿರಿ',
    howItWorks: 'HelpMate ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    accountSettings: 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    name: 'ಹೆಸರು',
    email: 'ಇಮೇಲ್',
    phone: 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ',
    location: 'ಸ್ಥಳ',
    language: 'ಭಾಷೆ',
    totalDonated: 'ಒಟ್ಟು ದಾನ ಮಾಡಿದ ವಸ್ತುಗಳು',
    notificationPrefs: 'ಅಧಿಸೂಚನೆ ಆದ್ಯತೆಗಳು',
    privacySecurity: 'ಗೌಪ್ಯತೆ ಮತ್ತು ಭದ್ರತೆ',
    helpSupport: 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    aboutApp: 'HelpMate ಬಗ್ಗೆ',
    available: 'ಲಭ್ಯವಿದೆ',
    myDeliveries: 'ನನ್ನ ವಿತರಣೆಗಳು',
    availableDeliveries: 'ಲಭ್ಯವಿರುವ ವಿತರಣೆಗಳು',
    deliveriesNeedHelp: 'ವಿತರಣೆಗಳಿಗೆ ನಿಮ್ಮ ಸಹಾಯ ಬೇಕು',
    noDeliveries: 'ಯಾವುದೇ ವಿತರಣೆಗಳು ಲಭ್ಯವಿಲ್ಲ',
    checkBackLater: 'ಹೊಸ ವಿತರಣಾ ವಿನಂತಿಗಳಿಗಾಗಿ ನಂತರ ಪರಿಶೀಲಿಸಿ',
    deliveryDetails: 'ವಿತರಣಾ ವಿವರಗಳು',
    pickupFrom: 'ನಿಂದ ಪಿಕಪ್',
    deliverTo: 'ಗೆ ವಿತರಿಸಿ',
    distance: 'ದೂರ',
    estimatedTime: 'ಅಂದಾಜು ಸಮಯ',
    acceptDelivery: 'ವಿತರಣೆಯನ್ನು ಸ್ವೀಕರಿಸಿ',
    back: 'ಹಿಂದೆ',
    activeDeliveries: 'ಸಕ್ರಿಯ ವಿತರಣೆಗಳು',
    noActiveDeliveries: 'ಸಕ್ರಿಯ ವಿತರಣೆಗಳಿಲ್ಲ',
    acceptDeliveriesToSee: 'ಅವುಗಳನ್ನು ಇಲ್ಲಿ ನೋಡಲು ವಿತರಣೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
    accepted: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    navigation: 'ನ್ಯಾವಿಗೇಶನ್',
    call: 'ಕರೆ',
    message: 'ಸಂದೇಶ',
    startDelivery: 'ವಿತರಣೆ ಪ್ರಾರಂಭಿಸಿ',
    viewMap: 'ನಕ್ಷೆಯನ್ನು ವೀಕ್ಷಿಸಿ',
    acceptedAt: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    callDonor: 'ದಾನಿಗೆ ಕರೆ ಮಾಡಿ',
    callRecipient: 'ಸ್ವೀಕರಿಸುವವರಿಗೆ ಕರೆ ಮಾಡಿ',
    // Onboarding & Auth translations
    skip: 'ಬಿಟ್ಟುಬಿಡಿ',
    continue: 'ಮುಂದುವರಿಸಿ',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    chooseYourLanguage: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    selectPreferredLanguage: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    yourDetails: 'ನಿಮ್ಮ ವಿವರಗಳು',
    letsGetToKnow: 'ನಿಮ್ಮನ್ನು ತಿಳಿದುಕೊಳ್ಳೋಣ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    enterFullName: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    emailOptional: 'ಇಮೇಲ್ (ಐಚ್ಛಿಕ)',
    enterEmail: 'your.email@example.com',
    nameRequired: 'ಹೆಸರು ಅಗತ್ಯವಿದೆ',
    nameTooShort: 'ಹೆಸರು ಕನಿಷ್ಠ 2 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು',
    phoneRequired: 'ಫೋನ್ ಸಂಖ್ಯೆ ಅಗತ್ಯವಿದೆ',
    phoneInvalid: 'ಫೋನ್ ಸಂಖ್ಯೆ 10 ಅಂಕೆಗಳಾಗಿರಬೇಕು',
    emailInvalid: 'ಅಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸ',
    digitsRemaining: 'ಅಂಕೆಗಳು ಉಳಿದಿವೆ',
    otpMessage: 'ಮುಂದಿನ ಹಂತದಲ್ಲಿ ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ಪರಿಶೀಲಿಸಲು ನಾವು ನಿಮಗೆ OTP ಕಳುಹಿಸುತ್ತೇವೆ.',
    aadharVerification: 'ಆಧಾರ್ ಪರಿಶೀಲನೆ',
    enterAadhar: 'ನಿಮ್ಮ 12-ಅಂಕಿಯ ಆಧಾರ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    aadharMustBe12: 'ಆಧಾರ್ ಸಂಖ್ಯೆ 12 ಅಂಕೆಗಳಾಗಿರಬೇಕು',
    dataSecure: 'ನಿಮ್ಮ ಡೇಟಾ ಸುರಕ್ಷಿತವಾಗಿದೆ',
    dataSecureDesc: 'ನಿಮ್ಮ ಆಧಾರ್ ಮಾಹಿತಿಯನ್ನು ರಕ್ಷಿಸಲು ನಾವು ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್ ಬಳಸುತ್ತೇವೆ. ನಿಮ್ಮ ಸಮ್ಮತಿಯಿಲ್ಲದೆ ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಎಂದಿಗೂ ಹಂಚಲಾಗುವುದಿಲ್ಲ.',
    whyAadhar: 'ನಮಗೆ ಆಧಾರ್ ಏಕೆ ಬೇಕು?',
    whyAadharPoint1: 'ವಂಚನೆಯನ್ನು ತಡೆಗಟ್ಟಲು ನಿಮ್ಮ ಗುರುತನ್ನು ಪರಿಶೀಲಿಸಿ',
    whyAadharPoint2: 'ಎಲ್ಲಾ ಬಳಕೆದಾರರಿಗೆ ಸುರಕ್ಷಿತ ವಹಿವಾಟುಗಳನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ',
    whyAadharPoint3: 'ಸಮುದಾಯದಲ್ಲಿ ನಂಬಿಕೆಯನ್ನು ನಿರ್ಮಿಸಿ',
    sendOtp: 'OTP ಕಳುಹಿಸಿ',
    verifyOtp: 'OTP ಪರಿಶೀಲಿಸಿ',
    codeSentTo: 'ಕೋಡ್ ಕಳುಹಿಸಲಾಗಿದೆ',
    resendCode: 'ಕೋಡ್ ಅನ್ನು ಮರು ಕಳುಹಿಸಿ',
    resendIn: 'ರಲ್ಲಿ ಮರು ಕಳುಹಿಸಿ',
    didntReceiveCode: 'ಕೋಡ್ ಸಿಗಲಿಲ್ಲವೇ? ನಿಮ್ಮ ಸಂದೇಶಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಅಥವಾ ಮರು ಕಳುಹಿಸಲು ಟೈಮರ್‌ಗಾಗಿ ಕಾಯಿರಿ.',
    verifyAndContinue: 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರಿಸಿ',
    howWillYouUse: 'ನೀವು HelpMate ಅನ್ನು ಹೇಗೆ ಬಳಸುತ್ತೀರಿ?',
    selectBestDescribes: 'ನಿಮ್ಮನ್ನು ಉತ್ತಮವಾಗಿ ವಿವರಿಸುವ ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ',
    donor: 'ದಾನಿ',
    donorDesc: 'ನಾನು ಅಗತ್ಯವಿರುವವರಿಗೆ ಸಹಾಯ ಮಾಡಲು ವಸ್ತುಗಳನ್ನು ದಾನ ಮಾಡಲು ಬಯಸುತ್ತೇನೆ',
    volunteerDriver: 'ಸ್ವಯಂಸೇವಕ ಚಾಲಕ',
    volunteerDriverDesc: 'ನಾನು ಅಗತ್ಯವಿರುವವರಿಗೆ ದಾನಗಳನ್ನು ತಲುಪಿಸಲು ಬಯಸುತ್ತೇನೆ',
    receiver: 'ಸ್ವೀಕರಿಸುವವರು',
    receiverDesc: 'ನನಗೆ ಅಥವಾ ನನ್ನ ಸಂಸ್ಥೆಗೆ ಸಹಾಯ ಅಥವಾ ದಾನಗಳ ಅಗತ್ಯವಿದೆ',
    verificationNote: 'ನಿಮ್ಮ ಆಯ್ಕೆಯ ಆಧಾರದ ಮೇಲೆ, ಮುಂದಿನ ಹಂತದಲ್ಲಿ ನೀವು ಹೆಚ್ಚುವರಿ ಪರಿಶೀಲನಾ ದಾಖಲೆಗಳನ್ನು ಒದಗಿಸಬೇಕಾಗಬಹುದು.',
    driverLicenseVerification: 'ಚಾಲನಾ ಪರವಾನಗಿ ಪರಿಶೀಲನೆ',
    driverLicenseDesc: 'ಸ್ವಯಂಸೇವಕ ಚಾಲಕರಾಗಿ, ನಾವು ನಿಮ್ಮ ಚಾಲನಾ ಪರವಾನಗಿಯನ್ನು ಪರಿಶೀಲಿಸಬೇಕಾಗಿದೆ',
    organizationVerification: 'ಸಂಸ್ಥೆಯ ಪರಿಶೀಲನೆ',
    organizationVerificationDesc: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂಸ್ಥೆಗೆ ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ಒದಗಿಸಿ',
    requiredDocuments: 'ಅಗತ್ಯ ದಾಖಲೆಗಳು',
    uploadDocuments: 'ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    clickOrDrag: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ ಅಥವಾ ಡ್ರ್ಯಾಗ್ ಮತ್ತು ಡ್ರಾಪ್ ಮಾಡಿ',
    dropFiles: 'ಫೈಲ್‌ಗಳನ್ನು ಇಲ್ಲಿ ಬಿಡಿ',
    fileFormats: 'PNG, JPG, ಅಥವಾ PDF (ಪ್ರತಿಯೊಂದೂ ಗರಿಷ್ಠ 10MB)',
    uploadedDocuments: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ದಾಖಲೆಗಳು',
    verificationProcess: 'ಪರಿಶೀಲನಾ ಪ್ರಕ್ರಿಯೆ',
    verificationProcessDesc: 'ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು 24-48 ಗಂಟೆಗಳಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ. ಪರಿಶೀಲಿಸಿದ ನಂತರ ನೀವು ಅಧಿಸೂಚನೆಯನ್ನು ಸ್ವೀಕರಿಸುತ್ತೀರಿ.',
    submitDocuments: 'ದಾಖಲೆಗಳನ್ನು ಸಲ್ಲಿಸಿ',
    skipVerifyLater: 'ಈಗ ಬಿಟ್ಟುಬಿಡಿ (ನಂತರ ಪರಿಶೀಲಿಸಿ)',
    communityPledge: 'ಸಮುದಾಯ ಸಮಗ್ರತೆ ಪ್ರತಿಜ್ಞೆ',
    maintainSafeCommunity: 'ಸುರಕ್ಷಿತ ಮತ್ತು ಪ್ರಾಮಾಣಿಕ ಸಮುದಾಯವನ್ನು ನಿರ್ವಹಿಸಲು ನಮಗೆ ಸಹಾಯ ಮಾಡಿ',
    iPledgeTo: 'ನಾನು ಪ್ರತಿಜ್ಞೆ ಮಾಡುತ್ತೇನೆ:',
    pledgePoint1: 'HelpMate ಅನ್ನು ಪ್ರಾಮಾಣಿಕವಾಗಿ ಮತ್ತು ಪಾರದರ್ಶಕವಾಗಿ ಬಳಸಿ',
    pledgePoint2: 'ಎಲ್ಲಾ ದಾನ ವಿನಂತಿಗಳಲ್ಲಿ ನಿಖರವಾದ ಮಾಹಿತಿಯನ್ನು ಒದಗಿಸಿ',
    pledgePoint3: 'ಎಲ್ಲಾ ಸಮುದಾಯ ಸದಸ್ಯರನ್ನು ಮತ್ತು ಅವರ ಕೊಡುಗೆಗಳನ್ನು ಗೌರವಿಸಿ',
    pledgePoint4: 'ಯಾವುದೇ ದುರುಪಯೋಗ ಅಥವಾ ವಂಚನೆಯ ಚಟುವಟಿಕೆಯನ್ನು ವರದಿ ಮಾಡಿ',
    pledgeWarning: 'ವಂಚನೆಯ ವಿನಂತಿಗಳು ಅಥವಾ ಕಿರುಕುಳ ಸೇರಿದಂತೆ ಈ ವೇದಿಕೆಯ ದುರುಪಯೋಗವು ಖಾತೆ ಅಮಾನತು ಮತ್ತು ಕಾನೂನು ಕ್ರಮಕ್ಕೆ ಕಾರಣವಾಗಬಹುದು.',
    agreeToPlege: 'ನಾನು ಸಮುದಾಯ ಸಮಗ್ರತೆ ಪ್ರತಿಜ್ಞೆಯನ್ನು ಓದಿದ್ದೇನೆ ಮತ್ತು ಒಪ್ಪುತ್ತೇನೆ ಮತ್ತು ದುರುಪಯೋಗದ ಪರಿಣಾಮಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೇನೆ',
    iAccept: 'ನಾನು ಒಪ್ಪುತ್ತೇನೆ',
    // Onboarding slides
    onboardingSlide1Title: 'ಸಂಪರ್ಕಿಸಿ ಮತ್ತು ಹಂಚಿಕೊಳ್ಳಿ',
    onboardingSlide1Desc: 'ಸಹಾಯಕ್ಕಾಗಿ ವಿನಂತಿಗಳನ್ನು ರಚಿಸಿ ಮತ್ತು ನಿಜವಾದ ವ್ಯತ್ಯಾಸವನ್ನು ಮಾಡಲು ಬಯಸುವ ನಿಮ್ಮ ಸಮುದಾಯದಲ್ಲಿ ಉದಾರ ದಾನಿಗಳೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ.',
    onboardingSlide2Title: 'ಬಹುಮಾನಗಳನ್ನು ಗಳಿಸಿ',
    onboardingSlide2Desc: 'ನೀವು ದಾನ ಮಾಡಿದಾಗ ಅಥವಾ ಅಗತ್ಯವಿರುವವರಿಗೆ ಸಹಾಯ ಮಾಡಿದಾಗ ಬೋನಸ್ ಅಂಕಗಳು ಮತ್ತು ಗುರುತಿಸುವಿಕೆಯನ್ನು ಪಡೆಯಿರಿ. ನಿಮ್ಮ ದಯೆ ಮುಖ್ಯವಾಗಿದೆ!',
    onboardingSlide3Title: 'ಸುರಕ್ಷಿತ ಮತ್ತು ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    onboardingSlide3Desc: 'ಸುರಕ್ಷಿತ, ಪಾರದರ್ಶಕ ದಾನಗಳು ಮತ್ತು ಸುರಕ್ಷಿತ ವಹಿವಾಟುಗಳೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿದ ಸದಸ್ಯರಿಗೆ ಸಹಾಯ ಮಾಡಿ. ನಂಬಿಕೆ ಪ್ರತಿ ಕ್ರಿಯೆಯಲ್ಲಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
